# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    - name: Codecov
      # You may pin to the exact commit or the version.
      # uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24
      uses: codecov/codecov-action@v5.4.3
      with:
        # Folder to search for coverage files. Default to the current working directory
        directory: coverage
        # On error, exit with non-zero code
        fail_ci_if_error: true
        # Comma-separated list of explicit files to upload. These will be added to the coverage files found for upload. If you wish to only upload the specified files, please consider using disable-search to disable uploading other files.
        name: ${{ matrix.node-version }}
        # Comma-separated list of plugins to run. Specify `noop` to turn off all plugins
        plugins: noop
        # Enable verbose logging
        verbose: true
              
